<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="PublicAPI.Shipped.txt" />
		<AdditionalFiles Include="PublicAPI.Unshipped.txt" />
	</ItemGroup>

</Project>
