<Project>
	<PropertyGroup Condition="'$(IsPackable)' != 'false'">
		<IsTrimmable>true</IsTrimmable>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsPackable)' != 'false'">
		<PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="all" />
		<None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
