<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Mubarrat.Fonts\Mubarrat.Fonts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="PublicAPI.Shipped.txt" />
		<AdditionalFiles Include="PublicAPI.Unshipped.txt" />
	</ItemGroup>

</Project>
